alias s="git status"
alias d="git diff"
alias a="git add"
alias co="git checkout"
alias gcm="git commit -m"
alias glo="git log --oneline"
alias ra="git rebase -i HEAD~$(git rev-list --count HEAD ^main)"